### ISSUE TITLE
make modified raspi-config available in pi-gen stages

### ISSUE THREAD

**Issue by JanLahmann** [JanLahmann/RasQberry-Two#27]
In general, it is preferred to make customisations in pi-gen stages using raspy-config in "nonint" mode, e.g. `raspi-config nonint do_vnc 0` (see https://github.com/JanLahmann/RasQberry-pi-gen/blob/2a03dbea8da55aa75605693aa0523ace922d7c80/stage5/02-enable-vnc/00-run.sh#L5C33-L5C61)

For that, we need to make the modified version of pi-gen available in our pi-gen stages.

**Comment by rishimathur14** [comment]
@JanLahmann assign this to me i will pick it up

**Comment by rishimathur14** [comment]
This is already taken care as part of the build so we can close.
