### ISSUE TITLE
Provide instructions how to use RPi Imager from Mac/Win command line with custom repository

### ISSUE THREAD

**Issue by JanLahmann** [JanLahmann/RasQberry-Two#28]

**Comment by JanLahmann** [comment]
Execute pi-imager from terminal: https://fleetstack.io/blog/access-pi-imager-from-terminal

How to Use Raspberry Pi's rpi-imager --cli Command on macOS: https://gist.github.com/bashtheshell/010d70f7643f171096ad9462ea86324b
Opening application using command line on Mac: https://www.wikihow.com/Open-Applications-Using-Terminal-on-Mac

**Comment by torstenandrecht** [comment]
@JanLahmann done
